---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: master
    cluster: home
rule_files:
- /etc/prometheus/config/alerts/*.yml
scrape_configs:

- job_name: prometheus
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /metrics
  static_configs:
  - targets:
    - localhost:9090

- job_name: grafana
  scrape_interval: 30s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - grafana:3000

- job_name: node_exporter
  scrape_interval: 30s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - node-exporter:9100

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
